# Form implementation generated from reading ui file 'SerialPortConfiguratorGUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(452, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setModal(True)
        self.bbConfirm = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.bbConfirm.setGeometry(QtCore.QRect(110, 210, 331, 24))
        self.bbConfirm.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.bbConfirm.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.bbConfirm.setObjectName("bbConfirm")
        self.lblStopBits = QtWidgets.QLabel(parent=Dialog)
        self.lblStopBits.setGeometry(QtCore.QRect(10, 145, 46, 16))
        self.lblStopBits.setObjectName("lblStopBits")
        self.lblPort = QtWidgets.QLabel(parent=Dialog)
        self.lblPort.setGeometry(QtCore.QRect(10, 5, 51, 16))
        self.lblPort.setObjectName("lblPort")
        self.comboBox_Parity = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_Parity.setGeometry(QtCore.QRect(200, 110, 240, 22))
        self.comboBox_Parity.setObjectName("comboBox_Parity")
        self.lblBaud = QtWidgets.QLabel(parent=Dialog)
        self.lblBaud.setGeometry(QtCore.QRect(10, 40, 27, 16))
        self.lblBaud.setObjectName("lblBaud")
        self.lblFlowControl = QtWidgets.QLabel(parent=Dialog)
        self.lblFlowControl.setGeometry(QtCore.QRect(10, 180, 66, 16))
        self.lblFlowControl.setObjectName("lblFlowControl")
        self.pbUpdatePorts = QtWidgets.QPushButton(parent=Dialog)
        self.pbUpdatePorts.setGeometry(QtCore.QRect(100, 5, 91, 22))
        self.pbUpdatePorts.setObjectName("pbUpdatePorts")
        self.lblDataBits = QtWidgets.QLabel(parent=Dialog)
        self.lblDataBits.setGeometry(QtCore.QRect(10, 75, 46, 16))
        self.lblDataBits.setObjectName("lblDataBits")
        self.comboBox_StopBits = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_StopBits.setGeometry(QtCore.QRect(200, 145, 240, 22))
        self.comboBox_StopBits.setObjectName("comboBox_StopBits")
        self.comboBox_Baud = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_Baud.setGeometry(QtCore.QRect(200, 40, 240, 22))
        self.comboBox_Baud.setObjectName("comboBox_Baud")
        self.comboBox_Port = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_Port.setGeometry(QtCore.QRect(200, 5, 240, 22))
        self.comboBox_Port.setObjectName("comboBox_Port")
        self.comboBox_DataBits = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_DataBits.setGeometry(QtCore.QRect(200, 75, 240, 22))
        self.comboBox_DataBits.setObjectName("comboBox_DataBits")
        self.lblParity = QtWidgets.QLabel(parent=Dialog)
        self.lblParity.setGeometry(QtCore.QRect(10, 110, 30, 16))
        self.lblParity.setObjectName("lblParity")
        self.splitter = QtWidgets.QSplitter(parent=Dialog)
        self.splitter.setGeometry(QtCore.QRect(100, 180, 341, 20))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.checkBox_SoftwareFlowCtrl = QtWidgets.QCheckBox(parent=self.splitter)
        self.checkBox_SoftwareFlowCtrl.setObjectName("checkBox_SoftwareFlowCtrl")
        self.checkBox_RtsCts = QtWidgets.QCheckBox(parent=self.splitter)
        self.checkBox_RtsCts.setObjectName("checkBox_RtsCts")
        self.checkBox_DsrDtr = QtWidgets.QCheckBox(parent=self.splitter)
        self.checkBox_DsrDtr.setObjectName("checkBox_DsrDtr")
        self.lblStopBits.setBuddy(self.comboBox_StopBits)
        self.lblPort.setBuddy(self.comboBox_Port)
        self.lblBaud.setBuddy(self.comboBox_Baud)
        self.lblDataBits.setBuddy(self.comboBox_DataBits)
        self.lblParity.setBuddy(self.comboBox_Parity)

        self.retranslateUi(Dialog)
        self.bbConfirm.accepted.connect(Dialog.accept) # type: ignore
        self.bbConfirm.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Serial Port Configurator"))
        self.lblStopBits.setText(_translate("Dialog", "Stop bits"))
        self.lblPort.setText(_translate("Dialog", "Com Port"))
        self.lblBaud.setText(_translate("Dialog", "Baud"))
        self.lblFlowControl.setText(_translate("Dialog", "Flow control"))
        self.pbUpdatePorts.setText(_translate("Dialog", "Update List"))
        self.lblDataBits.setText(_translate("Dialog", "Data bits"))
        self.lblParity.setText(_translate("Dialog", "Parity"))
        self.checkBox_SoftwareFlowCtrl.setText(_translate("Dialog", "Software Flow Control"))
        self.checkBox_RtsCts.setText(_translate("Dialog", "RTS/CTS"))
        self.checkBox_DsrDtr.setText(_translate("Dialog", "DSR/DTR"))
